/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.ManipulacionDatosFilas;

import Pantallas.ManipulacionDatosFilas.Actor.PanelActualizarFila_Actor;
import Pantallas.ManipulacionDatosFilas.Pelicula.PanelActualizarFila_Pelicula;
import Pantallas.ManipulacionDatosFilas.PersonajePelicula.PanelActualizarFila_PersonajePelicula;
import Pantallas.ManipulacionDatosFilas.PersonajeSerie.PanelActualizarFila_PersonajeSerie;
import Pantallas.ManipulacionDatosFilas.Serie.PanelActualizarFila_Serie;

/**
 *
 * @author isard
 */
public class ActualizarFila extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarFila
     */
    public ActualizarFila() {
        initComponents();
        panelCambiante.removeAll();
        panelCambiante.setLayout(new java.awt.BorderLayout());
        panelCambiante.add(new PanelActualizarFila_Pelicula(), java.awt.BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarFila = new javax.swing.JPanel();
        tituloInsertarFila = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonActualizarFila = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        textoActualizarFila2 = new javax.swing.JLabel();
        panelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tituloInsertarFila.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloInsertarFila.setText("ACTUALIZAR FILAS:");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a actualizar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonActualizarFila.setText("ACTUALIZAR");
        botonActualizarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarFilaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        textoActualizarFila2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoActualizarFila2.setText("Para actualizar la Fila presione el botón de ACTUALIZAR.");

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelActualizarFilaLayout = new javax.swing.GroupLayout(panelActualizarFila);
        panelActualizarFila.setLayout(panelActualizarFilaLayout);
        panelActualizarFilaLayout.setHorizontalGroup(
            panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(botonActualizarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                        .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelCambiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloInsertarFila)
                                    .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                                        .addComponent(textoSelectorTabla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(83, 83, 83)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                        .addComponent(textoActualizarFila2)
                        .addGap(109, 109, 109))))
        );
        panelActualizarFilaLayout.setVerticalGroup(
            panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(tituloInsertarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSelectorTabla)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonActualizarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoActualizarFila2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelActualizarFila, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
        panelCambiante.removeAll();

        panelCambiante.setLayout(new java.awt.BorderLayout());

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película":

                panelCambiante.add(
                        new PanelActualizarFila_Pelicula(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Serie":

                panelCambiante.add(
                        new PanelActualizarFila_Serie(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Actor":

                panelCambiante.add(
                        new PanelActualizarFila_Actor(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Personaje_Película":

                panelCambiante.add(
                        new PanelActualizarFila_PersonajePelicula(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Personaje_Serie":

                panelCambiante.add(
                        new PanelActualizarFila_PersonajeSerie(),
                        java.awt.BorderLayout.CENTER
                );

                break;
        }

        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonActualizarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarFilaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarFila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarFila;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel panelActualizarFila;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JLabel textoActualizarFila2;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloInsertarFila;
    // End of variables declaration//GEN-END:variables
}
