/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.CreacionEliminacionFilas.Actor;

import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author isard
 */
public class PanelEliminarFila_Actor extends javax.swing.JPanel {

    /**
     * Creates new form PanelEliminarFila
     */
    public PanelEliminarFila_Actor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarActor = new javax.swing.JScrollPane();
        tablaEliminarActor = new javax.swing.JTable();
        textoEliminar = new javax.swing.JLabel();
        textFieldIdentificadorEliminador = new javax.swing.JTextField();

        tablaEliminarActor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        eliminarActor.setViewportView(tablaEliminarActor);

        textoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEliminar.setText("Introduce el Identificador para eliminar:");

        textFieldIdentificadorEliminador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorEliminadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarActor, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIdentificadorEliminador, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarActor, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEliminar)
                    .addComponent(textFieldIdentificadorEliminador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIdentificadorEliminadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorEliminadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorEliminadorActionPerformed

    public JTable getTablaEliminarActor() {
        return tablaEliminarActor;
    }

    public JTextField getTextFieldIdentificadorEliminador() {
        return textFieldIdentificadorEliminador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane eliminarActor;
    private javax.swing.JTable tablaEliminarActor;
    private javax.swing.JTextField textFieldIdentificadorEliminador;
    private javax.swing.JLabel textoEliminar;
    // End of variables declaration//GEN-END:variables
}
