/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ManipulacionDatosFilas.PersonajePelicula;

import javax.swing.JTextField;

/**
 *
 * @author isard
 */
public class PanelInsertarFila_PersonajePelicula extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarFila
     */
    public PanelInsertarFila_PersonajePelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        textoCódigo = new javax.swing.JLabel();
        textoCódigoActor = new javax.swing.JLabel();
        textoTipo = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        textFieldCódigoActor = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldTipo = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        textoCódigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCódigo.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(81, 113, 0, 0);
        add(textoCódigo, gridBagConstraints);

        textoCódigoActor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCódigoActor.setText("Código Actor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 113, 0, 0);
        add(textoCódigoActor, gridBagConstraints);

        textoTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoTipo.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 113, 0, 0);
        add(textoTipo, gridBagConstraints);

        textoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 113, 0, 0);
        add(textoNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(83, 33, 0, 117);
        add(textFieldCodigo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 33, 0, 117);
        add(textFieldCódigoActor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 33, 0, 117);
        add(textFieldNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 33, 149, 117);
        add(textFieldTipo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTextFieldCodigo() {
        return textFieldCodigo;
    }

    public JTextField getTextFieldNombre() {
        return textFieldNombre;
    }

    public JTextField getTextFieldTipo() {
        return textFieldTipo;
    }

    public JTextField getTextFieldCódigoActor() {
        return textFieldCódigoActor;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldCódigoActor;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTipo;
    private javax.swing.JLabel textoCódigo;
    private javax.swing.JLabel textoCódigoActor;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoTipo;
    // End of variables declaration//GEN-END:variables
}
