/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.CreacionEliminacionFilas;

import Pantallas.CreacionEliminacionFilas.Actor.PanelEliminarFila_Actor;
import Pantallas.CreacionEliminacionFilas.Pelicula.PanelEliminarFila_Pelicula;
import Pantallas.CreacionEliminacionFilas.PersonajePelicula.PanelEliminarFila_PersonajePelicula;
import Pantallas.CreacionEliminacionFilas.PersonajeSerie.PanelEliminarFila_PersonajeSerie;
import Pantallas.CreacionEliminacionFilas.Serie.PanelEliminarFila_Serie;
import java.sql.Connection;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import javax.swing.SwingUtilities;
import Pantallas.ManipulacionDatosFilas.ActualizarFila;
import Servicios.BaseDatos.Actualizar_EliminarDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class EliminarFila extends javax.swing.JFrame {

    private javax.swing.JPanel panelActual;

    /**
     * Creates new form EliminarfILA
     */
    public EliminarFila() {
        initComponents();
        this.setLocationRelativeTo(null);

        panelCambiante.setLayout(new java.awt.BorderLayout());

        // Cargar Película por defecto
        SwingUtilities.invokeLater(() -> {
            PanelEliminarFila_Pelicula p = new PanelEliminarFila_Pelicula();
            panelActual = p;

            panelCambiante.add(p, java.awt.BorderLayout.CENTER);
            panelCambiante.revalidate();
            panelCambiante.repaint();

            SwingUtilities.invokeLater(() -> {
                ActualizarFila.cargarTablaYListener(
                        "pelicula",
                        "codigo",
                        p.getTablaEliminarPelicula(),
                        p.getTextFieldIdentificadorEliminador()
                );
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarFila = new javax.swing.JPanel();
        textoEliminar2 = new javax.swing.JLabel();
        botonEliminarFila = new javax.swing.JButton();
        tituloEliminarFila = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        panelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textoEliminar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEliminar2.setText("Para eliminar una fila presiona el botón ELIMINAR FILA.");

        botonEliminarFila.setText("ELIMINAR FILA");
        botonEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFilaActionPerformed(evt);
            }
        });

        tituloEliminarFila.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloEliminarFila.setText("ELIMINAR FILA:");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a eliminar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEliminarFilaLayout = new javax.swing.GroupLayout(panelEliminarFila);
        panelEliminarFila.setLayout(panelEliminarFilaLayout);
        panelEliminarFilaLayout.setHorizontalGroup(
            panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(21, 21, 21))
            .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(textoSelectorTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(textoEliminar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(botonEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(tituloEliminarFila)
                        .addGap(286, 286, 286))))
        );
        panelEliminarFilaLayout.setVerticalGroup(
            panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloEliminarFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(botonEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(18, 18, 18))
        );

        getContentPane().add(panelEliminarFila, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFilaActionPerformed
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        try {
            String opcion = selectorTabla.getSelectedItem().toString();

            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas eliminar esta fila?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }

            switch (opcion) {

                case "Película" -> {
                    PanelEliminarFila_Pelicula p
                            = (PanelEliminarFila_Pelicula) panelActual;

                    int codigo = Integer.parseInt(
                            p.getTextFieldIdentificadorEliminador().getText()
                    );

                    Actualizar_EliminarDatos.eliminar(
                            "pelicula", codigo, con
                    );

                    LeerDatos.consultarTabla(
                            "pelicula",
                            "codigo",
                            con,
                            p.getTablaEliminarPelicula()
                    );
                }

                case "Serie" -> {
                    PanelEliminarFila_Serie s
                            = (PanelEliminarFila_Serie) panelActual;

                    int codigo = Integer.parseInt(
                            s.getTextFieldIdentificadorEliminador().getText()
                    );

                    Actualizar_EliminarDatos.eliminar(
                            "serie", codigo, con
                    );

                    LeerDatos.consultarTabla(
                            "serie",
                            "codigo",
                            con,
                            s.getTablaEliminarSerie()
                    );
                }

                case "Actor" -> {
                    PanelEliminarFila_Actor a
                            = (PanelEliminarFila_Actor) panelActual;

                    int codigo = Integer.parseInt(
                            a.getTextFieldIdentificadorEliminador().getText()
                    );

                    Actualizar_EliminarDatos.eliminar(
                            "actor", codigo, con
                    );

                    LeerDatos.consultarTabla(
                            "actor",
                            "codigo",
                            con,
                            a.getTablaEliminarActor()
                    );
                }

                case "Personaje_Película" -> {
                    PanelEliminarFila_PersonajePelicula pp
                            = (PanelEliminarFila_PersonajePelicula) panelActual;

                    int codigoPelicula = Integer.parseInt(
                            pp.getTextFieldIdentificadorEliminadorComplejo1().getText()
                    );

                    int codigoActor = Integer.parseInt(
                            pp.getTextFieldIdentificadorEliminadorComplejo2().getText()
                    );

                    Actualizar_EliminarDatos.eliminarPersonaje_Pelicula(
                            codigoActor,
                            codigoPelicula,
                            con
                    );

                    LeerDatos.consultarTabla(
                            "personaje_pelicula",
                            "codigo_pelicula",
                            con,
                            pp.getTablaEliminarPersonajePelicula()
                    );
                }

                case "Personaje_Serie" -> {
                    PanelEliminarFila_PersonajeSerie ps
                            = (PanelEliminarFila_PersonajeSerie) panelActual;

                    int codigoSerie = Integer.parseInt(
                            ps.getTextFieldIdentificadorEliminadorComplejo1().getText()
                    );

                    int codigoActor = Integer.parseInt(
                            ps.getTextFieldIdentificadorEliminadorComplejo2().getText()
                    );

                    Actualizar_EliminarDatos.eliminarPersonaje_Serie(
                            codigoActor,
                            codigoSerie,
                            con
                    );

                    LeerDatos.consultarTabla(
                            "personaje_serie",
                            "codigo_serie",
                            con,
                            ps.getTablaEliminarPersonajeSerie()
                    );
                }
            }

            JOptionPane.showMessageDialog(this, "Fila eliminada correctamente");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al eliminar la fila");
        }

    }//GEN-LAST:event_botonEliminarFilaActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:

        panelCambiante.removeAll();
        panelCambiante.setLayout(new java.awt.BorderLayout());

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película" -> {
                PanelEliminarFila_Pelicula p = new PanelEliminarFila_Pelicula();
                panelActual = p;
                panelCambiante.add(p, java.awt.BorderLayout.CENTER);

                SwingUtilities.invokeLater(() -> {
                    ActualizarFila.cargarTablaYListener(
                            "pelicula",
                            "codigo",
                            p.getTablaEliminarPelicula(),
                            p.getTextFieldIdentificadorEliminador()
                    );
                });
            }

            case "Serie" -> {
                PanelEliminarFila_Serie s = new PanelEliminarFila_Serie();
                panelActual = s;
                panelCambiante.add(s, java.awt.BorderLayout.CENTER);

                SwingUtilities.invokeLater(() -> {
                    ActualizarFila.cargarTablaYListener(
                            "serie",
                            "codigo",
                            s.getTablaEliminarSerie(),
                            s.getTextFieldIdentificadorEliminador()
                    );
                });
            }

            case "Actor" -> {
                PanelEliminarFila_Actor a = new PanelEliminarFila_Actor();
                panelActual = a;
                panelCambiante.add(a, java.awt.BorderLayout.CENTER);

                SwingUtilities.invokeLater(() -> {
                    ActualizarFila.cargarTablaYListener(
                            "actor",
                            "codigo",
                            a.getTablaEliminarActor(),
                            a.getTextFieldIdentificadorEliminador()
                    );
                });
            }

            case "Personaje_Película" -> {
                PanelEliminarFila_PersonajePelicula pp
                        = new PanelEliminarFila_PersonajePelicula();
                panelActual = pp;
                panelCambiante.add(pp, java.awt.BorderLayout.CENTER);

                SwingUtilities.invokeLater(() -> {
                    ActualizarFila.cargarTablaYListener(
                            "personaje_pelicula",
                            "codigo_pelicula",
                            pp.getTablaEliminarPersonajePelicula(),
                            pp.getTextFieldIdentificadorEliminadorComplejo1(),
                            pp.getTextFieldIdentificadorEliminadorComplejo2()
                    );
                });
            }

            case "Personaje_Serie" -> {
                PanelEliminarFila_PersonajeSerie ps
                        = new PanelEliminarFila_PersonajeSerie();
                panelActual = ps;
                panelCambiante.add(ps, java.awt.BorderLayout.CENTER);

                SwingUtilities.invokeLater(() -> {
                    ActualizarFila.cargarTablaYListener(
                            "personaje_serie",
                            "codigo_serie",
                            ps.getTablaEliminarPersonajeSerie(),
                            ps.getTextFieldIdentificadorEliminadorComplejo1(),
                            ps.getTextFieldIdentificadorEliminadorComplejo2()
                    );
                });
            }
        }

        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarFila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarFila;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelEliminarFila;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JLabel textoEliminar2;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloEliminarFila;
    // End of variables declaration//GEN-END:variables
}
