/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.CreacionEliminacionFilas;

import Pantallas.CreacionEliminacionFilas.Actor.PanelEliminarFila_Actor;
import Pantallas.CreacionEliminacionFilas.Pelicula.PanelEliminarFila_Pelicula;
import Pantallas.CreacionEliminacionFilas.PersonajePelicula.PanelEliminarFila_PersonajePelicula;
import Pantallas.CreacionEliminacionFilas.PersonajeSerie.PanelEliminarFila_PersonajeSerie;
import Pantallas.CreacionEliminacionFilas.Serie.PanelEliminarFila_Serie;

/**
 *
 * @author isard
 */
public class EliminarFila extends javax.swing.JFrame {

    /**
     * Creates new form EliminarfILA
     */
    public EliminarFila() {
        initComponents();
        panelCambiante.setLayout(new java.awt.BorderLayout());
        panelCambiante.add(new PanelEliminarFila_Pelicula(), java.awt.BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarFila = new javax.swing.JPanel();
        textoEliminar2 = new javax.swing.JLabel();
        botonEliminarFila = new javax.swing.JButton();
        tituloEliminarFila = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        textoEliminar = new javax.swing.JLabel();
        textFieldIdentificadorEliminar = new javax.swing.JTextField();
        panelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textoEliminar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEliminar2.setText("Para eliminar una fila presiona el botón ELIMINAR FILA.");

        botonEliminarFila.setText("ELIMINAR FILA");
        botonEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFilaActionPerformed(evt);
            }
        });

        tituloEliminarFila.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloEliminarFila.setText("ELIMINAR FILA:");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a eliminar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        textoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEliminar.setText("Introduce el Identificador para eliminar:");

        textFieldIdentificadorEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEliminarFilaLayout = new javax.swing.GroupLayout(panelEliminarFila);
        panelEliminarFila.setLayout(panelEliminarFilaLayout);
        panelEliminarFilaLayout.setHorizontalGroup(
            panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(textoSelectorTabla)
                        .addGap(33, 33, 33)
                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(textoEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldIdentificadorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(tituloEliminarFila)
                        .addGap(151, 151, 151))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(botonEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarFilaLayout.createSequentialGroup()
                        .addComponent(textoEliminar2)
                        .addGap(115, 115, 115))))
        );
        panelEliminarFilaLayout.setVerticalGroup(
            panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarFilaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEliminarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEliminar)
                    .addComponent(textFieldIdentificadorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(botonEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(botonSalir)
                .addGap(18, 18, 18))
        );

        getContentPane().add(panelEliminarFila, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarFilaActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
        panelCambiante.removeAll();

        panelCambiante.setLayout(new java.awt.BorderLayout());

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película":

                panelCambiante.add(
                        new PanelEliminarFila_Pelicula(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Serie":

                panelCambiante.add(
                        new PanelEliminarFila_Serie(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Actor":

                panelCambiante.add(
                        new PanelEliminarFila_Actor(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Personaje_Película":

                panelCambiante.add(
                        new PanelEliminarFila_PersonajePelicula(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Personaje_Serie":

                panelCambiante.add(
                        new PanelEliminarFila_PersonajeSerie(),
                        java.awt.BorderLayout.CENTER
                );

                break;
        }

        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void textFieldIdentificadorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarFila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarFila;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelEliminarFila;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JTextField textFieldIdentificadorEliminar;
    private javax.swing.JLabel textoEliminar;
    private javax.swing.JLabel textoEliminar2;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloEliminarFila;
    // End of variables declaration//GEN-END:variables
}
