/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.CreacionEliminacionFilas;

/**
 *
 * @author isard
 */
public class EliminarFila extends javax.swing.JFrame {

    /**
     * Creates new form EliminarfILA
     */
    public EliminarFila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarFila = new javax.swing.JPanel();
        textoConsulta2 = new javax.swing.JLabel();
        botonEliminarFila = new javax.swing.JButton();
        jScrollPanelEliminar = new javax.swing.JScrollPane();
        tablaEliminarFila = new javax.swing.JTable();
        tituloConsultarFila = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        textoEliminar = new javax.swing.JLabel();
        textFieldIdentificadorEliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textoConsulta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsulta2.setText("Para consultar una fila presiona el botón ELIMINAR FILA.");

        botonEliminarFila.setText("ELIMINAR FILA");
        botonEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFilaActionPerformed(evt);
            }
        });

        tablaEliminarFila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEliminarFila.setColumnSelectionAllowed(true);
        jScrollPanelEliminar.setViewportView(tablaEliminarFila);

        tituloConsultarFila.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloConsultarFila.setText("ELIMINAR FILA:");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a consultar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        textoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEliminar.setText("Introduce el Identificador para eliminar:");

        textFieldIdentificadorEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarFilaLayout = new javax.swing.GroupLayout(panelActualizarFila);
        panelActualizarFila.setLayout(panelActualizarFilaLayout);
        panelActualizarFilaLayout.setHorizontalGroup(
            panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarFilaLayout.createSequentialGroup()
                        .addComponent(jScrollPanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
            .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(textoSelectorTabla)
                        .addGap(18, 18, 18)
                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(textoEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldIdentificadorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(botonEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(textoConsulta2))
                    .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(tituloConsultarFila)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelActualizarFilaLayout.setVerticalGroup(
            panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarFilaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(tituloConsultarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(jScrollPanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelActualizarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEliminar)
                    .addComponent(textFieldIdentificadorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(botonEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        getContentPane().add(panelActualizarFila, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarFilaActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void textFieldIdentificadorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarFila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarFila;
    private javax.swing.JButton botonSalir;
    private javax.swing.JScrollPane jScrollPanelEliminar;
    private javax.swing.JPanel panelActualizarFila;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JTable tablaEliminarFila;
    private javax.swing.JTextField textFieldIdentificadorEliminar;
    private javax.swing.JLabel textoConsulta2;
    private javax.swing.JLabel textoEliminar;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloConsultarFila;
    // End of variables declaration//GEN-END:variables
}
