/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.CreacionEliminacionFilas;

import Servicios.BaseDatos.ServicioBase_de_Datos;
import Servicios.Ficheros.Exportar.*;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import java.sql.*;
/**
 *
 * @author isard
 */
public class ExportarTabla extends javax.swing.JFrame {

    /**
     * Creates new form ExportarTabla
     */
    public ExportarTabla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExportarTabla = new javax.swing.JPanel();
        botonTXT = new javax.swing.JButton();
        tituloExportarTabla = new javax.swing.JLabel();
        botonBinario = new javax.swing.JButton();
        botonCSV = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        iconoCSV = new javax.swing.JLabel();
        botonJSON = new javax.swing.JButton();
        iconoBinario = new javax.swing.JLabel();
        iconoJSON = new javax.swing.JLabel();
        iconoTXT = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        botonTXT.setText("TXT");
        botonTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTXTActionPerformed(evt);
            }
        });

        tituloExportarTabla.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        tituloExportarTabla.setText("Selecciona el formato a exportar la tabla:");

        botonBinario.setText("BINARIO");
        botonBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBinarioActionPerformed(evt);
            }
        });

        botonCSV.setText("CSV");
        botonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCSVActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        iconoCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoCSV.png"))); // NOI18N

        botonJSON.setText("JSON");
        botonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJSONActionPerformed(evt);
            }
        });

        iconoBinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoBinario.png"))); // NOI18N
        iconoBinario.setMinimumSize(new java.awt.Dimension(177, 122));
        iconoBinario.setName(""); // NOI18N

        iconoJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoJSON.png"))); // NOI18N
        iconoJSON.setName(""); // NOI18N

        iconoTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoTXT.png"))); // NOI18N

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a exportar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExportarTablaLayout = new javax.swing.GroupLayout(panelExportarTabla);
        panelExportarTabla.setLayout(panelExportarTablaLayout);
        panelExportarTablaLayout.setHorizontalGroup(
            panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExportarTablaLayout.createSequentialGroup()
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExportarTablaLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(botonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelExportarTablaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(iconoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoCSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconoJSON, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(botonJSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(panelExportarTablaLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(textoSelectorTabla)
                .addGap(18, 18, 18)
                .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExportarTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExportarTablaLayout.createSequentialGroup()
                        .addComponent(tituloExportarTabla)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExportarTablaLayout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addGap(14, 14, 14))))
        );
        panelExportarTablaLayout.setVerticalGroup(
            panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExportarTablaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloExportarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExportarTablaLayout.createSequentialGroup()
                        .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconoJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelExportarTablaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(panelExportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelExportarTablaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelExportarTablaLayout.createSequentialGroup()
                        .addComponent(iconoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(botonSalir)
                .addGap(25, 25, 25))
        );

        getContentPane().add(panelExportarTabla, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTXTActionPerformed
        // TODO add your handling code here:
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        try {
            String opcion = selectorTabla.getSelectedItem().toString().trim();

            String tabla = switch (opcion) {
                case "Película" ->
                    "pelicula";
                case "Serie" ->
                    "serie";
                case "Actor" ->
                    "actor";
                case "Personaje_Película" ->
                    "personaje_pelicula";
                case "Personaje_Serie" ->
                    "personaje_serie";
                default ->
                    throw new RuntimeException("Tabla inválida");
            };

            List<String> datos = obtenerDatosTabla(con, tabla);

            Exportar.exporatTXT(datos, tabla);

            JOptionPane.showMessageDialog(this, "✔ Exportado TXT correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al exportar TXT", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonTXTActionPerformed

    private void botonBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBinarioActionPerformed
        // TODO add your handling code here:
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        try {
            String opcion = selectorTabla.getSelectedItem().toString().trim();

            String tabla = switch (opcion) {
                case "Película" ->
                    "pelicula";
                case "Serie" ->
                    "serie";
                case "Actor" ->
                    "actor";
                case "Personaje_Película" ->
                    "personaje_pelicula";
                case "Personaje_Serie" ->
                    "personaje_serie";
                default ->
                    throw new RuntimeException("Tabla inválida");
            };

            List<String> datos = obtenerDatosTabla(con, tabla);

            Exportar.exportarBINARIO(datos, tabla);

            JOptionPane.showMessageDialog(this, "✔ Exportado BINARIO correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al exportar BINARIO", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBinarioActionPerformed

    private void botonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCSVActionPerformed
        // TODO add your handling code here:
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        try {
            String opcion = selectorTabla.getSelectedItem().toString().trim();

            String tabla = switch (opcion) {
                case "Película" ->
                    "pelicula";
                case "Serie" ->
                    "serie";
                case "Actor" ->
                    "actor";
                case "Personaje_Película" ->
                    "personaje_pelicula";
                case "Personaje_Serie" ->
                    "personaje_serie";
                default ->
                    throw new RuntimeException("Tabla inválida");
            };

            List<String> datos = obtenerDatosTabla(con, tabla);

            Exportar.exportarCSV(datos, tabla);

            JOptionPane.showMessageDialog(this, "✔ Exportado CSV correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al exportar CSV", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCSVActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJSONActionPerformed
        // TODO add your handling code here:
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        try {
            String opcion = selectorTabla.getSelectedItem().toString().trim();

            String tabla = switch (opcion) {
                case "Película" ->
                    "pelicula";
                case "Serie" ->
                    "serie";
                case "Actor" ->
                    "actor";
                case "Personaje_Película" ->
                    "personaje_pelicula";
                case "Personaje_Serie" ->
                    "personaje_serie";
                default ->
                    throw new RuntimeException("Tabla inválida");
            };

            List<String> datos = obtenerDatosTabla(con, tabla);

            Exportar.exportarJSON(datos, tabla);

            JOptionPane.showMessageDialog(this, "✔ Exportado JSON correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al exportar JSON", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonJSONActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportarTabla().setVisible(true);
            }
        });
    }

    public List<String> obtenerDatosTabla(Connection con, String tabla) {
        List<String> datos = new ArrayList<>();

        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM " + tabla);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                switch (tabla) {

                    case "pelicula" ->
                        datos.add(
                                rs.getInt("codigo") + ";"
                                + rs.getString("titulo") + ";"
                                + rs.getString("director") + ";"
                                + rs.getInt("año_estreno") + ";"
                                + rs.getInt("duracion")
                        );

                    case "serie" ->
                        datos.add(
                                rs.getInt("codigo") + ";"
                                + rs.getString("titulo") + ";"
                                + rs.getString("creador") + ";"
                                + rs.getString("años_emision") + ";"
                                + rs.getInt("temporadas") + ";"
                                + rs.getInt("episodios")
                        );

                    case "actor" ->
                        datos.add(
                                rs.getInt("codigo") + ";"
                                + rs.getString("nombre") + ";"
                                + rs.getString("fecha_nacimiento") + ";"
                                + rs.getString("lugar_residencia") + ";"
                                + rs.getString("nacionalidad")
                        );

                    case "personaje_pelicula" ->
                        datos.add(
                                rs.getInt("codigo_pelicula") + ";"
                                + rs.getInt("codigo_actor_P") + ";"
                                + rs.getString("nombre") + ";"
                                + rs.getString("tipo")
                        );

                    case "personaje_serie" ->
                        datos.add(
                                rs.getInt("codigo_serie") + ";"
                                + rs.getInt("codigo_actor_S") + ";"
                                + rs.getString("nombre") + ";"
                                + rs.getString("tipo") + ";"
                                + rs.getString("duracion")
                        );
                }
            }

            rs.close();
            ps.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        return datos;
    }

    public static String convertirTabla(String opcion) {
        return switch (opcion) {
            case "Película" ->
                "pelicula";
            case "Serie" ->
                "serie";
            case "Actor" ->
                "actor";
            case "Personaje_Película" ->
                "personaje_pelicula";
            case "Personaje_Serie" ->
                "personaje_serie";
            default ->
                throw new IllegalArgumentException("Tabla no válida: " + opcion);
        };
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBinario;
    private javax.swing.JButton botonCSV;
    private javax.swing.JButton botonJSON;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTXT;
    private javax.swing.JLabel iconoBinario;
    private javax.swing.JLabel iconoCSV;
    private javax.swing.JLabel iconoJSON;
    private javax.swing.JLabel iconoTXT;
    private javax.swing.JPanel panelExportarTabla;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloExportarTabla;
    // End of variables declaration//GEN-END:variables
}
