/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.CreacionEliminacionFilas;

/**
 *
 * @author isard
 */
public class ImportarTabla extends javax.swing.JFrame {

    /**
     * Creates new form ImportarTabla
     */
    public ImportarTabla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImportarTabla = new javax.swing.JPanel();
        botonTXT = new javax.swing.JButton();
        tituloImportarTabla = new javax.swing.JLabel();
        botonBinario = new javax.swing.JButton();
        botonCSV = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        iconoCSV = new javax.swing.JLabel();
        botonJSON = new javax.swing.JButton();
        iconoBinario = new javax.swing.JLabel();
        iconoJSON = new javax.swing.JLabel();
        iconoTXT = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        botonTXT.setText("TXT");
        botonTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTXTActionPerformed(evt);
            }
        });

        tituloImportarTabla.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        tituloImportarTabla.setText("Selecciona el formato a importar la tabla:");

        botonBinario.setText("BINARIO");
        botonBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBinarioActionPerformed(evt);
            }
        });

        botonCSV.setText("CSV");
        botonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCSVActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        iconoCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoCSV.png"))); // NOI18N

        botonJSON.setText("JSON");
        botonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJSONActionPerformed(evt);
            }
        });

        iconoBinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoBinario.png"))); // NOI18N
        iconoBinario.setMinimumSize(new java.awt.Dimension(177, 122));
        iconoBinario.setName(""); // NOI18N

        iconoJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoJSON.png"))); // NOI18N
        iconoJSON.setName(""); // NOI18N

        iconoTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoTXT.png"))); // NOI18N

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a importar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImportarTablaLayout = new javax.swing.GroupLayout(panelImportarTabla);
        panelImportarTabla.setLayout(panelImportarTablaLayout);
        panelImportarTablaLayout.setHorizontalGroup(
            panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportarTablaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportarTablaLayout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportarTablaLayout.createSequentialGroup()
                        .addComponent(tituloImportarTabla)
                        .addGap(192, 192, 192))))
            .addGroup(panelImportarTablaLayout.createSequentialGroup()
                .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImportarTablaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconoCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelImportarTablaLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(textoSelectorTabla)
                        .addGap(18, 18, 18)
                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelImportarTablaLayout.setVerticalGroup(
            panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportarTablaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloImportarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 70, Short.MAX_VALUE)
                .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImportarTablaLayout.createSequentialGroup()
                        .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconoJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImportarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelImportarTablaLayout.createSequentialGroup()
                        .addComponent(iconoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(botonSalir)
                .addGap(22, 22, 22))
        );

        getContentPane().add(panelImportarTabla, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTXTActionPerformed

    private void botonBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBinarioActionPerformed

    private void botonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCSVActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonJSONActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportarTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportarTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBinario;
    private javax.swing.JButton botonCSV;
    private javax.swing.JButton botonJSON;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTXT;
    private javax.swing.JLabel iconoBinario;
    private javax.swing.JLabel iconoCSV;
    private javax.swing.JLabel iconoJSON;
    private javax.swing.JLabel iconoTXT;
    private javax.swing.JPanel panelImportarTabla;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloImportarTabla;
    // End of variables declaration//GEN-END:variables
}
