/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ConsultasFilas.Actor;

import java.sql.*;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author isard
 */
public class PanelConsultarFila_Actor extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarFila
     */
    public PanelConsultarFila_Actor() {
        initComponents();

        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        LeerDatos.consultarTabla(
                "actor",
                "codigo",
                con,
                tablaConsultarActor
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarActor = new javax.swing.JScrollPane();
        tablaConsultarActor = new javax.swing.JTable();
        textoConsultar = new javax.swing.JLabel();
        textFieldIdentificadorConsultador = new javax.swing.JTextField();

        tablaConsultarActor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consultarActor.setViewportView(tablaConsultarActor);

        textoConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsultar.setText("Introduce el Identificador para consultar:");

        textFieldIdentificadorConsultador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorConsultadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultarActor, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(textoConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIdentificadorConsultador, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultarActor, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConsultar)
                    .addComponent(textFieldIdentificadorConsultador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIdentificadorConsultadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorConsultadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorConsultadorActionPerformed

    public JTable getTablaConsultarActor() {
        return tablaConsultarActor;
    }

    public JTextField getTextFieldIdentificadorConsultador() {
        return textFieldIdentificadorConsultador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane consultarActor;
    private javax.swing.JTable tablaConsultarActor;
    private javax.swing.JTextField textFieldIdentificadorConsultador;
    private javax.swing.JLabel textoConsultar;
    // End of variables declaration//GEN-END:variables
}
