/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ManipulacionDatosFilas.PersonajeSerie;

/**
 *
 * @author isard
 */
public class PanelInsertarFila_PersonajeSerie extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarFila
     */
    public PanelInsertarFila_PersonajeSerie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialog1 = new javax.swing.JDialog();
        textoCódigoSerie = new javax.swing.JLabel();
        textoCódigoActor = new javax.swing.JLabel();
        textoTipo = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textFieldCodigoSerie = new javax.swing.JTextField();
        textFieldCódigoActor = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldTipo = new javax.swing.JTextField();
        textoDuracion = new javax.swing.JLabel();
        textoEpisodios = new javax.swing.JLabel();
        textFieldEpisodios = new javax.swing.JTextField();
        textFieldDuracion = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridBagLayout());

        textoCódigoSerie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCódigoSerie.setText("Código Serie:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 107, 0, 0);
        add(textoCódigoSerie, gridBagConstraints);

        textoCódigoActor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCódigoActor.setText("Código Actor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 107, 0, 0);
        add(textoCódigoActor, gridBagConstraints);

        textoTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoTipo.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 107, 0, 0);
        add(textoTipo, gridBagConstraints);

        textoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 107, 0, 0);
        add(textoNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 62, 0, 94);
        add(textFieldCodigoSerie, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 62, 0, 94);
        add(textFieldCódigoActor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 62, 0, 94);
        add(textFieldNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 62, 0, 94);
        add(textFieldTipo, gridBagConstraints);

        textoDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoDuracion.setText("Duración:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 107, 0, 0);
        add(textoDuracion, gridBagConstraints);

        textoEpisodios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEpisodios.setText("Episodios:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 107, 0, 0);
        add(textoEpisodios, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 62, 0, 94);
        add(textFieldEpisodios, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 62, 60, 94);
        add(textFieldDuracion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JTextField textFieldCodigoSerie;
    private javax.swing.JTextField textFieldCódigoActor;
    private javax.swing.JTextField textFieldDuracion;
    private javax.swing.JTextField textFieldEpisodios;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTipo;
    private javax.swing.JLabel textoCódigoActor;
    private javax.swing.JLabel textoCódigoSerie;
    private javax.swing.JLabel textoDuracion;
    private javax.swing.JLabel textoEpisodios;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoTipo;
    // End of variables declaration//GEN-END:variables
}
