/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ConsultasFilas.PersonajeSerie;

import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author isard
 */
public class PanelConsultarFila_PersonajeSerie extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarFila
     */
    public PanelConsultarFila_PersonajeSerie() {
        initComponents();

        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        LeerDatos.consultarTabla(
                "personaje_serie",
                "codigo_serie",
                con,
                tablaConsultarPersonajeSerie
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarPersonajeSerie = new javax.swing.JScrollPane();
        tablaConsultarPersonajeSerie = new javax.swing.JTable();
        textoConsultarCompleja1 = new javax.swing.JLabel();
        textoConsultarCompleja2 = new javax.swing.JLabel();
        textFieldIdentificadorConsultadorComplejo2 = new javax.swing.JTextField();
        textFieldIdentificadorConsultadorComplejo1 = new javax.swing.JTextField();

        tablaConsultarPersonajeSerie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consultarPersonajeSerie.setViewportView(tablaConsultarPersonajeSerie);

        textoConsultarCompleja1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsultarCompleja1.setText("Introduce el Identificador de Película para consultar:");

        textoConsultarCompleja2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsultarCompleja2.setText("Introduce el Identificador de Actor para consultar:");

        textFieldIdentificadorConsultadorComplejo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorConsultadorComplejo2ActionPerformed(evt);
            }
        });

        textFieldIdentificadorConsultadorComplejo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorConsultadorComplejo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarPersonajeSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoConsultarCompleja1)
                            .addComponent(textoConsultarCompleja2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textFieldIdentificadorConsultadorComplejo2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textFieldIdentificadorConsultadorComplejo1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(134, 134, 134)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultarPersonajeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConsultarCompleja1)
                    .addComponent(textFieldIdentificadorConsultadorComplejo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConsultarCompleja2)
                    .addComponent(textFieldIdentificadorConsultadorComplejo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIdentificadorConsultadorComplejo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorConsultadorComplejo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorConsultadorComplejo2ActionPerformed

    private void textFieldIdentificadorConsultadorComplejo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorConsultadorComplejo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorConsultadorComplejo1ActionPerformed

    public JTable getTablaConsultarPersonajeSerie() {
        return tablaConsultarPersonajeSerie;
    }

    public JTextField getTextFieldIdentificadorConsultadorComplejo1() {
        return textFieldIdentificadorConsultadorComplejo1;
    }

    public JTextField getTextFieldIdentificadorConsultadorComplejo2() {
        return textFieldIdentificadorConsultadorComplejo2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane consultarPersonajeSerie;
    private javax.swing.JTable tablaConsultarPersonajeSerie;
    private javax.swing.JTextField textFieldIdentificadorConsultadorComplejo1;
    private javax.swing.JTextField textFieldIdentificadorConsultadorComplejo2;
    private javax.swing.JLabel textoConsultarCompleja1;
    private javax.swing.JLabel textoConsultarCompleja2;
    // End of variables declaration//GEN-END:variables
}
