/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Pantallas.ConsultasFilas;
import Pantallas.ConsultasFilas.Actor.PanelConsultarFilas_Actor;
import Pantallas.ConsultasFilas.Pelicula.PanelConsultarFilas_Pelicula;
import Pantallas.ConsultasFilas.PersonajePelicula.PanelConsultarFilas_PersonajePelicula;
import Pantallas.ConsultasFilas.PersonajeSerie.PanelConsultarFilas_PersonajeSerie;
import Pantallas.ConsultasFilas.Serie.PanelConsultarFilas_Serie;
/**
 *
 * @author isard
 */
public class ConsultarFilas extends javax.swing.JFrame {

    /** Creates new form ConsultarFilas */
    public ConsultarFilas() {
        initComponents();
        panelCambiante.setLayout(new java.awt.BorderLayout());
        panelCambiante.add(new PanelConsultarFilas_Pelicula(), java.awt.BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultarFilas = new javax.swing.JPanel();
        tituloConsultarFilas = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        panelCambiante = new javax.swing.JPanel();
        textoConsultarFilas2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tituloConsultarFilas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloConsultarFilas.setText("CONSULTAR FILAS:");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a consultar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        textoConsultarFilas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsultarFilas2.setText("Para ordenar las tablas presione el título de la fila a querer ordenar.");

        javax.swing.GroupLayout panelConsultarFilasLayout = new javax.swing.GroupLayout(panelConsultarFilas);
        panelConsultarFilas.setLayout(panelConsultarFilasLayout);
        panelConsultarFilasLayout.setHorizontalGroup(
            panelConsultarFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarFilasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarFilasLayout.createSequentialGroup()
                        .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilasLayout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(botonSalir)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelConsultarFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloConsultarFilas)
                            .addGroup(panelConsultarFilasLayout.createSequentialGroup()
                                .addComponent(textoSelectorTabla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(157, 157, 157))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoConsultarFilas2)
                .addGap(137, 137, 137))
        );
        panelConsultarFilasLayout.setVerticalGroup(
            panelConsultarFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarFilasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloConsultarFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsultarFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoConsultarFilas2)
                .addGap(36, 36, 36)
                .addComponent(botonSalir)
                .addGap(19, 19, 19))
        );

        getContentPane().add(panelConsultarFilas, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
        panelCambiante.removeAll();

        panelCambiante.setLayout(new java.awt.BorderLayout());

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película":

                panelCambiante.add(
                        new PanelConsultarFilas_Pelicula(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Serie":

                panelCambiante.add(
                        new PanelConsultarFilas_Serie(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Actor":

                panelCambiante.add(
                        new PanelConsultarFilas_Actor(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Personaje_Película":

                panelCambiante.add(
                        new PanelConsultarFilas_PersonajePelicula(),
                        java.awt.BorderLayout.CENTER
                );

                break;

            case "Personaje_Serie":

                panelCambiante.add(
                        new PanelConsultarFilas_PersonajeSerie(),
                        java.awt.BorderLayout.CENTER
                );

                break;
        }

        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFilas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelConsultarFilas;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JLabel textoConsultarFilas2;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloConsultarFilas;
    // End of variables declaration//GEN-END:variables

}
