/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.ConsultasFilas;

import Pantallas.ConsultasFilas.Actor.PanelConsultarFila_Actor;
import Pantallas.ConsultasFilas.Pelicula.PanelConsultarFila_Pelicula;
import Pantallas.ConsultasFilas.PersonajePelicula.PanelConsultarFila_PersonajePelicula;
import Pantallas.ConsultasFilas.PersonajeSerie.PanelConsultarFila_PersonajeSerie;
import Pantallas.ConsultasFilas.Serie.PanelConsultarFila_Serie;
import java.sql.Connection;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import javax.swing.JTable;

/**
 *
 * @author isard
 */
public class ConsultarFila extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarFila
     */
    public ConsultarFila() {
        initComponents();
        panelCambiante.setLayout(new java.awt.BorderLayout());

        PanelConsultarFila_Pelicula panel = new PanelConsultarFila_Pelicula();
        panelCambiante.add(panel, java.awt.BorderLayout.CENTER);

        configurarSeleccion(panel.getTablaConsultarPelicula());

        panelCambiante.revalidate();
        panelCambiante.repaint();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultarFila = new javax.swing.JPanel();
        textoConsulta2 = new javax.swing.JLabel();
        botonConsultarFila = new javax.swing.JButton();
        tituloConsultarFila = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        textoConsultar = new javax.swing.JLabel();
        textFieldIdentificadorConsultador = new javax.swing.JTextField();
        panelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textoConsulta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsulta2.setText("Para consultar una fila presiona el botón CONSULTAR FILA.");

        botonConsultarFila.setText("CONSULTAR FILA");
        botonConsultarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarFilaActionPerformed(evt);
            }
        });

        tituloConsultarFila.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloConsultarFila.setText("CONSULTAR FILA");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a consultar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        textoConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsultar.setText("Introduce el Identificador para consultar:");

        textFieldIdentificadorConsultador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorConsultadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelConsultarFilaLayout = new javax.swing.GroupLayout(panelConsultarFila);
        panelConsultarFila.setLayout(panelConsultarFilaLayout);
        panelConsultarFilaLayout.setHorizontalGroup(
            panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelConsultarFilaLayout.createSequentialGroup()
                .addGroup(panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelConsultarFilaLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(textoConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldIdentificadorConsultador, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(textoSelectorTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(botonConsultarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(textoConsulta2)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(tituloConsultarFila)
                        .addGap(225, 225, 225))))
        );
        panelConsultarFilaLayout.setVerticalGroup(
            panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarFilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloConsultarFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConsultar)
                    .addComponent(textFieldIdentificadorConsultador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(botonConsultarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(botonSalir)
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelConsultarFila, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarFilaActionPerformed
        // TODO add your handling code here:
        String opcion = selectorTabla.getSelectedItem().toString();

        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        switch (opcion) {

            case "Película":
                LeerDatos.consultarFila(
                        "pelicula",
                        "codigo",
                        textFieldIdentificadorConsultador.getText(),
                        con,
                        ((PanelConsultarFila_Pelicula) panelCambiante.getComponent(0)).getTablaConsultarPelicula()
                );
                break;

            case "Serie":
                LeerDatos.consultarFila(
                        "serie",
                        "codigo",
                        textFieldIdentificadorConsultador.getText(),
                        con,
                        ((PanelConsultarFila_Serie) panelCambiante.getComponent(0)).getTablaConsultarSerie()
                );
                break;

            case "Actor":
                LeerDatos.consultarFila(
                        "actor",
                        "codigo",
                        textFieldIdentificadorConsultador.getText(),
                        con,
                        ((PanelConsultarFila_Actor) panelCambiante.getComponent(0)).getTablaConsultarActor()
                );
                break;

            case "Personaje_Película":
                LeerDatos.consultarFila(
                        "personaje_pelicula",
                        "codigo_pelicula",
                        textFieldIdentificadorConsultador.getText(),
                        con,
                        ((PanelConsultarFila_PersonajePelicula) panelCambiante.getComponent(0)).getTablaConsultarPersonajePelicula()
                );
                break;

            case "Personaje_Serie":
                LeerDatos.consultarFila(
                        "personaje_serie",
                        "codigo_serie",
                        textFieldIdentificadorConsultador.getText(),
                        con,
                        ((PanelConsultarFila_PersonajeSerie) panelCambiante.getComponent(0)).getTablaConsultarPersonajeSerie()
                );
                break;
        }
    }//GEN-LAST:event_botonConsultarFilaActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        // TODO add your handling code here:
        panelCambiante.removeAll();
        panelCambiante.setLayout(new java.awt.BorderLayout());

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película":

                PanelConsultarFila_Pelicula panel = new PanelConsultarFila_Pelicula();
                panelCambiante.add(panel, java.awt.BorderLayout.CENTER);
                configurarSeleccion(panel.getTablaConsultarPelicula());

                break;

            case "Serie":

                PanelConsultarFila_Serie panelSerie = new PanelConsultarFila_Serie();
                panelCambiante.add(panelSerie, java.awt.BorderLayout.CENTER);
                configurarSeleccion(panelSerie.getTablaConsultarSerie());

                break;

            case "Actor":

                PanelConsultarFila_Actor panelActor = new PanelConsultarFila_Actor();
                panelCambiante.add(panelActor, java.awt.BorderLayout.CENTER);
                configurarSeleccion(panelActor.getTablaConsultarActor());

                break;

            case "Personaje_Película":

                PanelConsultarFila_PersonajePelicula panelPP = new PanelConsultarFila_PersonajePelicula();
                panelCambiante.add(panelPP, java.awt.BorderLayout.CENTER);
                configurarSeleccion(panelPP.getTablaConsultarPersonajePelicula());

                break;

            case "Personaje_Serie":

                PanelConsultarFila_PersonajeSerie panelPS = new PanelConsultarFila_PersonajeSerie();
                panelCambiante.add(panelPS, java.awt.BorderLayout.CENTER);
                configurarSeleccion(panelPS.getTablaConsultarPersonajeSerie());

                break;
        }

        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void textFieldIdentificadorConsultadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorConsultadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorConsultadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFila().setVisible(true);
            }
        });
    }

    private void configurarSeleccion(javax.swing.JTable tabla) {
        tabla.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tabla.getSelectedRow() != -1) {
                Object id = tabla.getValueAt(tabla.getSelectedRow(), 0);
                textFieldIdentificadorConsultador.setText(id.toString());
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarFila;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelConsultarFila;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JTextField textFieldIdentificadorConsultador;
    private javax.swing.JLabel textoConsulta2;
    private javax.swing.JLabel textoConsultar;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloConsultarFila;
    // End of variables declaration//GEN-END:variables
}
