/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas.ConsultasFilas;

import Pantallas.ConsultasFilas.Actor.PanelConsultarFila_Actor;
import Pantallas.ConsultasFilas.Pelicula.PanelConsultarFila_Pelicula;
import Pantallas.ConsultasFilas.PersonajePelicula.PanelConsultarFila_PersonajePelicula;
import Pantallas.ConsultasFilas.PersonajeSerie.PanelConsultarFila_PersonajeSerie;
import Pantallas.ConsultasFilas.Serie.PanelConsultarFila_Serie;
import java.sql.Connection;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import javax.swing.SwingUtilities;
import Pantallas.ManipulacionDatosFilas.ActualizarFila;

/**
 *
 * @author isard
 */
public class ConsultarFila extends javax.swing.JFrame {

    private javax.swing.JPanel panelActual;

    public ConsultarFila() {
        initComponents();
        this.setLocationRelativeTo(null); //...

        panelCambiante.setLayout(new java.awt.BorderLayout());

        //...
        SwingUtilities.invokeLater(() -> {
            PanelConsultarFila_Pelicula p = new PanelConsultarFila_Pelicula();
            panelActual = p;

            panelCambiante.add(p, java.awt.BorderLayout.CENTER);
            panelCambiante.revalidate();
            panelCambiante.repaint();

            SwingUtilities.invokeLater(() -> {
                ActualizarFila.cargarTablaYListener(
                        "pelicula",
                        "codigo",
                        p.getTablaConsultarPelicula(),
                        p.getTextFieldIdentificadorConsultador()
                );
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultarFila = new javax.swing.JPanel();
        textoConsulta2 = new javax.swing.JLabel();
        botonConsultarFila = new javax.swing.JButton();
        tituloConsultarFila = new javax.swing.JLabel();
        textoSelectorTabla = new javax.swing.JLabel();
        selectorTabla = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        panelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textoConsulta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsulta2.setText("Para consultar una fila presiona el botón CONSULTAR FILA.");

        botonConsultarFila.setText("CONSULTAR FILA");
        botonConsultarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarFilaActionPerformed(evt);
            }
        });

        tituloConsultarFila.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        tituloConsultarFila.setText("CONSULTAR FILA");

        textoSelectorTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSelectorTabla.setText("Seleccione la tabla a consultar:");

        selectorTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Serie", "Actor", "Personaje_Película", "Personaje_Serie" }));
        selectorTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTablaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelConsultarFilaLayout = new javax.swing.GroupLayout(panelConsultarFila);
        panelConsultarFila.setLayout(panelConsultarFilaLayout);
        panelConsultarFilaLayout.setHorizontalGroup(
            panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(textoSelectorTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(tituloConsultarFila)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(botonConsultarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(textoConsulta2)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarFilaLayout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addGap(14, 14, 14))))
            .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelConsultarFilaLayout.setVerticalGroup(
            panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarFilaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloConsultarFila)
                .addGap(8, 8, 8)
                .addGroup(panelConsultarFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSelectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(botonConsultarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botonSalir)
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelConsultarFila, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void selectorTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTablaActionPerformed
        panelCambiante.removeAll();

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película":
                panelActual = new PanelConsultarFila_Pelicula();
                break;

            case "Serie":
                panelActual = new PanelConsultarFila_Serie();
                break;

            case "Actor":
                panelActual = new PanelConsultarFila_Actor();
                break;

            case "Personaje_Película":
                panelActual = new PanelConsultarFila_PersonajePelicula();
                break;

            case "Personaje_Serie":
                panelActual = new PanelConsultarFila_PersonajeSerie();
                break;
        }

        panelCambiante.add(panelActual);
        panelCambiante.revalidate();
        panelCambiante.repaint();

     
        inicializarSeleccionSegunPanel();
    }//GEN-LAST:event_selectorTablaActionPerformed

    private void botonConsultarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarFilaActionPerformed
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();
        String opcion = selectorTabla.getSelectedItem().toString();

        try {

            switch (opcion) {

                case "Película": {
                    PanelConsultarFila_Pelicula p
                            = (PanelConsultarFila_Pelicula) panelActual;

                    LeerDatos.consultarFila(
                            "pelicula",
                            "codigo",
                            Integer.parseInt(p.getTextFieldIdentificadorConsultador().getText()),
                            con,
                            p.getTablaConsultarPelicula()
                    );
                    break;
                }

                case "Serie": {
                    PanelConsultarFila_Serie s
                            = (PanelConsultarFila_Serie) panelActual;

                    LeerDatos.consultarFila(
                            "serie",
                            "codigo",
                            Integer.parseInt(s.getTextFieldIdentificadorConsultador().getText()),
                            con,
                            s.getTablaConsultarSerie()
                    );
                    break;
                }

                case "Actor": {
                    PanelConsultarFila_Actor a
                            = (PanelConsultarFila_Actor) panelActual;

                    LeerDatos.consultarFila(
                            "actor",
                            "codigo",
                            Integer.parseInt(a.getTextFieldIdentificadorConsultador().getText()),
                            con,
                            a.getTablaConsultarActor()
                    );
                    break;
                }

                case "Personaje_Película": {
                    PanelConsultarFila_PersonajePelicula pp
                            = (PanelConsultarFila_PersonajePelicula) panelActual;

                    LeerDatos.consultarFilaCompuesta(
                            "personaje_pelicula",
                            "codigo_pelicula",
                            Integer.parseInt(pp.getTextFieldIdentificadorConsultadorComplejo1().getText()),
                            "codigo_actor_P",
                            Integer.parseInt(pp.getTextFieldIdentificadorConsultadorComplejo2().getText()),
                            con,
                            pp.getTablaConsultarPersonajePelicula()
                    );
                    break;
                }

                case "Personaje_Serie": {
                    PanelConsultarFila_PersonajeSerie ps
                            = (PanelConsultarFila_PersonajeSerie) panelActual;

                    LeerDatos.consultarFilaCompuesta(
                            "personaje_serie",
                            "codigo_serie",
                            Integer.parseInt(ps.getTextFieldIdentificadorConsultadorComplejo1().getText()),
                            "codigo_actor_S",
                            Integer.parseInt(ps.getTextFieldIdentificadorConsultadorComplejo2().getText()),
                            con,
                            ps.getTablaConsultarPersonajeSerie()
                    );
                    break;
                }
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los códigos deben ser números válidos");
            e.printStackTrace();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al consultar");
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFila.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFila().setVisible(true);
            }
        });
    }

    private void inicializarSeleccionSegunPanel() {

        String opcion = selectorTabla.getSelectedItem().toString();

        switch (opcion) {

            case "Película":
                configurarSeleccion(((PanelConsultarFila_Pelicula) panelActual).getTablaConsultarPelicula());
                break;

            case "Serie":
                configurarSeleccion(((PanelConsultarFila_Serie) panelActual).getTablaConsultarSerie());
                break;

            case "Actor":
                configurarSeleccion(((PanelConsultarFila_Actor) panelActual).getTablaConsultarActor());
                break;

            case "Personaje_Película":
                configurarSeleccion(((PanelConsultarFila_PersonajePelicula) panelActual).getTablaConsultarPersonajePelicula());
                break;

            case "Personaje_Serie":
                configurarSeleccion(((PanelConsultarFila_PersonajeSerie) panelActual).getTablaConsultarPersonajeSerie());
                break;
        }
    }

    private void configurarSeleccion(javax.swing.JTable tabla) {
        tabla.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting() && tabla.getSelectedRow() != -1) {

                int row = tabla.getSelectedRow();
                String opcion = selectorTabla.getSelectedItem().toString();

                switch (opcion) {

                    case "Película": {
                        PanelConsultarFila_Pelicula panel
                                = (PanelConsultarFila_Pelicula) panelActual;

                        panel.getTextFieldIdentificadorConsultador()
                                .setText(tabla.getValueAt(row, 0).toString());
                        break;
                    }

                    case "Serie": {
                        PanelConsultarFila_Serie panel
                                = (PanelConsultarFila_Serie) panelActual;

                        panel.getTextFieldIdentificadorConsultador()
                                .setText(tabla.getValueAt(row, 0).toString());
                        break;
                    }

                    case "Actor": {
                        PanelConsultarFila_Actor panel
                                = (PanelConsultarFila_Actor) panelActual;

                        panel.getTextFieldIdentificadorConsultador()
                                .setText(tabla.getValueAt(row, 0).toString());
                        break;
                    }

                    case "Personaje_Película": {
                        PanelConsultarFila_PersonajePelicula panel
                                = (PanelConsultarFila_PersonajePelicula) panelActual;

                        panel.getTextFieldIdentificadorConsultadorComplejo1()
                                .setText(tabla.getValueAt(row, 0).toString());

                        panel.getTextFieldIdentificadorConsultadorComplejo2()
                                .setText(tabla.getValueAt(row, 1).toString());
                        break;
                    }

                    case "Personaje_Serie": {
                        PanelConsultarFila_PersonajeSerie panel
                                = (PanelConsultarFila_PersonajeSerie) panelActual;

                        panel.getTextFieldIdentificadorConsultadorComplejo1()
                                .setText(tabla.getValueAt(row, 0).toString());

                        panel.getTextFieldIdentificadorConsultadorComplejo2()
                                .setText(tabla.getValueAt(row, 1).toString());
                        break;
                    }
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarFila;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelConsultarFila;
    private javax.swing.JComboBox<String> selectorTabla;
    private javax.swing.JLabel textoConsulta2;
    private javax.swing.JLabel textoSelectorTabla;
    private javax.swing.JLabel tituloConsultarFila;
    // End of variables declaration//GEN-END:variables
}
