/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ManipulacionDatosFilas.Pelicula;

/**
 *
 * @author isard
 */
public class PanelInsertarFila extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarFila
     */
    public PanelInsertarFila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        textoCódigo = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoLugarResidencia = new javax.swing.JLabel();
        textoFechaNacimiento = new javax.swing.JLabel();
        textoNacionalidad = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldFechaNacimiento = new javax.swing.JTextField();
        textFieldLugarRsidencia = new javax.swing.JTextField();
        textFieldNacionalidad = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        textoCódigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCódigo.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 91, 0, 0);
        add(textoCódigo, gridBagConstraints);

        textoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 91, 0, 0);
        add(textoNombre, gridBagConstraints);

        textoLugarResidencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoLugarResidencia.setText("Lugar Residencia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 91, 0, 0);
        add(textoLugarResidencia, gridBagConstraints);

        textoFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoFechaNacimiento.setText("Fecha Nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 91, 0, 0);
        add(textoFechaNacimiento, gridBagConstraints);

        textoNacionalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoNacionalidad.setText("Nacionalidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 91, 0, 0);
        add(textoNacionalidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 12, 0, 79);
        add(textFieldCodigo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 12, 0, 79);
        add(textFieldNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 12, 0, 79);
        add(textFieldFechaNacimiento, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 12, 0, 79);
        add(textFieldLugarRsidencia, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 12, 125, 79);
        add(textFieldNacionalidad, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldFechaNacimiento;
    private javax.swing.JTextField textFieldLugarRsidencia;
    private javax.swing.JTextField textFieldNacionalidad;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JLabel textoCódigo;
    private javax.swing.JLabel textoFechaNacimiento;
    private javax.swing.JLabel textoLugarResidencia;
    private javax.swing.JLabel textoNacionalidad;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
