/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ConsultasFilas.InformesMultitabla;

import java.util.logging.*;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import java.sql.Connection;
import javax.swing.JTable;

/**
 *
 * @author isard
 */
public class PanelInforme6 extends javax.swing.JPanel {

    /**
     * Creates new form Informe6
     */
    public PanelInforme6() {
        initComponents();
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        String sql
                = "SELECT s.titulo, COUNT(DISTINCT ps.codigo_actor_S) "
                + "FROM serie s "
                + "LEFT JOIN personaje_serie ps ON s.codigo = ps.codigo_serie "
                + "GROUP BY s.titulo";

        LeerDatos.consultarSQL(sql, con, tablaInforme);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoInforme1 = new javax.swing.JLabel();
        textoInforme2 = new javax.swing.JLabel();
        scrollPanelInforme = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();

        textoInforme1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme1.setText("Consultar el título de cada serie junto con el número total de actores que participan en ella. Este informe");

        textoInforme2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme2.setText("informe ayuda a entender cómo resumir información numérica vinculada a una entidad.");

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPanelInforme.setViewportView(tablaInforme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scrollPanelInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme1)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme2)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textoInforme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoInforme2)
                .addGap(24, 24, 24)
                .addComponent(scrollPanelInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelInforme;
    private javax.swing.JTable tablaInforme;
    private javax.swing.JLabel textoInforme1;
    private javax.swing.JLabel textoInforme2;
    // End of variables declaration//GEN-END:variables
}
