/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ConsultasFilas.InformesMultitabla;

import java.util.logging.*;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import java.sql.Connection;
import javax.swing.JTable;

/**
 *
 * @author isard
 */
public class PanelInforme9 extends javax.swing.JPanel {

    /**
     * Creates new form Informe9
     */
    public PanelInforme9() {
        initComponents();
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        String sql
                = "SELECT * FROM pelicula "
                + "WHERE año_estreno BETWEEN 2010 AND 2020 "
                + "AND titulo LIKE '%Misterio%' "
                + "AND duracion > 120";

        LeerDatos.consultarSQL(sql, con, tablaInforme);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoInforme2 = new javax.swing.JLabel();
        scrollPanelInforme = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();
        textoInforme1 = new javax.swing.JLabel();

        textoInforme2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme2.setText("palabra \"Misterio\" y su duración sea superior a 120 minutos.");

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPanelInforme.setViewportView(tablaInforme);

        textoInforme1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme1.setText("Consultar las películas estrenadas entre los años 2010 y 2020 cuyo título contenga la");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scrollPanelInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme1)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme2)
                        .addGap(229, 229, 229))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textoInforme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoInforme2)
                .addGap(24, 24, 24)
                .addComponent(scrollPanelInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelInforme;
    private javax.swing.JTable tablaInforme;
    private javax.swing.JLabel textoInforme1;
    private javax.swing.JLabel textoInforme2;
    // End of variables declaration//GEN-END:variables
}
