/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ConsultasFilas.InformesMultitabla;

import java.util.logging.*;
import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import java.sql.Connection;
import javax.swing.JTable;

/**
 *
 * @author isard
 */
public class PanelInforme1 extends javax.swing.JPanel {

    /**
     * Creates new form Informe1
     */
    public PanelInforme1() {
        initComponents();
        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();
        String sql
                = "SELECT p.titulo, p.año_estreno, p.duracion, a.nombre, pp.nombre "
                + "FROM pelicula p "
                + "JOIN personaje_pelicula pp ON pp.codigo_pelicula = p.codigo "
                + "JOIN actor a ON pp.codigo_actor_P = a.codigo "
                + "ORDER BY p.duracion DESC";

        LeerDatos.consultarSQL(sql, con, tablaInforme);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoInforme1 = new javax.swing.JLabel();
        textoInforme2 = new javax.swing.JLabel();
        textoInforme3 = new javax.swing.JLabel();
        scrollPanelInforme = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();

        textoInforme1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme1.setText("Consultar el título, el año de estreno y la duración de todas las películas, indicando para cada película,");

        textoInforme2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme2.setText("los nombres de sus actores y los nombres de sus personajes interpretados. Este informe deberá estar ordenado por la");

        textoInforme3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInforme3.setText(" duración de la película de forma descendente.");

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPanelInforme.setViewportView(tablaInforme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scrollPanelInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme2)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme1)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoInforme3)
                        .addGap(273, 273, 273))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoInforme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoInforme2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoInforme3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanelInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelInforme;
    private javax.swing.JTable tablaInforme;
    private javax.swing.JLabel textoInforme1;
    private javax.swing.JLabel textoInforme2;
    private javax.swing.JLabel textoInforme3;
    // End of variables declaration//GEN-END:variables
}
