/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ManipulacionDatosFilas.Serie;

/**
 *
 * @author isard
 */
public class PanelInsertarFila_Serie extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertarFila
     */
    public PanelInsertarFila_Serie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoCódigo = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JLabel();
        textoAñoEmision = new javax.swing.JLabel();
        textoCreador = new javax.swing.JLabel();
        textFieldCodigo = new javax.swing.JTextField();
        textFieldTítulo = new javax.swing.JTextField();
        textFieldCreador = new javax.swing.JTextField();
        textFieldAñoEmision = new javax.swing.JTextField();
        textoEpisodios = new javax.swing.JLabel();
        textoTemporadas = new javax.swing.JLabel();
        textFieldTemporadas = new javax.swing.JTextField();
        textFieldDEpisodios = new javax.swing.JTextField();

        textoCódigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCódigo.setText("Código:");

        textoTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoTitulo.setText("Título:");

        textoAñoEmision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoAñoEmision.setText("Año Emisión");

        textoCreador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCreador.setText("Creador:");

        textoEpisodios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEpisodios.setText("Episodios:");

        textoTemporadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoTemporadas.setText("Temporadas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoCódigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEpisodios)
                            .addComponent(textoTemporadas)
                            .addComponent(textoAñoEmision))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldAñoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoCreador)
                        .addGap(93, 93, 93)
                        .addComponent(textFieldCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCreador)
                    .addComponent(textFieldCreador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAñoEmision)
                    .addComponent(textFieldAñoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTemporadas)
                    .addComponent(textFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEpisodios)
                    .addComponent(textFieldDEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textFieldAñoEmision;
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldCreador;
    private javax.swing.JTextField textFieldDEpisodios;
    private javax.swing.JTextField textFieldTemporadas;
    private javax.swing.JTextField textFieldTítulo;
    private javax.swing.JLabel textoAñoEmision;
    private javax.swing.JLabel textoCreador;
    private javax.swing.JLabel textoCódigo;
    private javax.swing.JLabel textoEpisodios;
    private javax.swing.JLabel textoTemporadas;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
