/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;
import Pantallas.ConsultasFilas.*;
/**
 *
 * @author isard
 */
public class MenúConsultas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarFila
     */
    public MenúConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenúConsultas = new javax.swing.JPanel();
        botonConsultaFilas = new javax.swing.JButton();
        tituloMenúConsultas = new javax.swing.JLabel();
        botonConsultaDatos = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        iconoConsultaDatos = new javax.swing.JLabel();
        iconoConsultarFilas = new javax.swing.JLabel();
        botonConsultaFila = new javax.swing.JButton();
        iconoConsultaFila = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelMenúConsultas.setName(""); // NOI18N
        panelMenúConsultas.setPreferredSize(new java.awt.Dimension(932, 426));

        botonConsultaFilas.setText("CONSULTAR FILAS");
        botonConsultaFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaFilasActionPerformed(evt);
            }
        });

        tituloMenúConsultas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        tituloMenúConsultas.setText("Seleccione la operación de Consulta que desea realizar");

        botonConsultaDatos.setText("CONSULTAR DATOS INSERTADOS");
        botonConsultaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaDatosActionPerformed(evt);
            }
        });

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        iconoConsultaDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoDocumento.png"))); // NOI18N

        iconoConsultarFilas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lupa.png"))); // NOI18N

        botonConsultaFila.setText("CONSULTAR FILA");
        botonConsultaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaFilaActionPerformed(evt);
            }
        });

        iconoConsultaFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoConsultarFila.png"))); // NOI18N

        javax.swing.GroupLayout panelMenúConsultasLayout = new javax.swing.GroupLayout(panelMenúConsultas);
        panelMenúConsultas.setLayout(panelMenúConsultasLayout);
        panelMenúConsultasLayout.setHorizontalGroup(
            panelMenúConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenúConsultasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenúConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenúConsultasLayout.createSequentialGroup()
                        .addComponent(botonAtras)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenúConsultasLayout.createSequentialGroup()
                        .addComponent(tituloMenúConsultas)
                        .addGap(140, 140, 140))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenúConsultasLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(botonConsultaFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonConsultaFilas)
                .addGap(129, 129, 129)
                .addComponent(botonConsultaDatos)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenúConsultasLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(iconoConsultaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(iconoConsultarFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(iconoConsultaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        panelMenúConsultasLayout.setVerticalGroup(
            panelMenúConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenúConsultasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tituloMenúConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelMenúConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoConsultarFilas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoConsultaDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoConsultaFila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenúConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultaFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(botonAtras)
                .addContainerGap())
        );

        getContentPane().add(panelMenúConsultas, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        new MenúPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonConsultaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaDatosActionPerformed
        // TODO add your handling code here:
        new DatosInsertados().setVisible(true);
    }//GEN-LAST:event_botonConsultaDatosActionPerformed

    private void botonConsultaFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaFilasActionPerformed
        // TODO add your handling code here:
        new ConsultarFilas().setVisible(true);
    }//GEN-LAST:event_botonConsultaFilasActionPerformed

    private void botonConsultaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaFilaActionPerformed
        // TODO add your handling code here:
        new ConsultarFila().setVisible(true);
       
    }//GEN-LAST:event_botonConsultaFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenúConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonConsultaDatos;
    private javax.swing.JButton botonConsultaFila;
    private javax.swing.JButton botonConsultaFilas;
    private javax.swing.JLabel iconoConsultaDatos;
    private javax.swing.JLabel iconoConsultaFila;
    private javax.swing.JLabel iconoConsultarFilas;
    private javax.swing.JPanel panelMenúConsultas;
    private javax.swing.JLabel tituloMenúConsultas;
    // End of variables declaration//GEN-END:variables
}
