/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.ConsultasFilas.Serie;

import Servicios.BaseDatos.LeerDatos;
import Servicios.BaseDatos.ServicioBase_de_Datos;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author isard
 */
public class PanelConsultarFila_Serie extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarFila
     */
    public PanelConsultarFila_Serie() {
        initComponents();

        Connection con = ServicioBase_de_Datos.inciarBase_De_Datos();

        LeerDatos.consultarTabla(
                "serie",
                "codigo",
                con,
                tablaConsultarSerie
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarSerie = new javax.swing.JScrollPane();
        tablaConsultarSerie = new javax.swing.JTable();
        textoConsultar = new javax.swing.JLabel();
        textFieldIdentificadorConsultador = new javax.swing.JTextField();

        tablaConsultarSerie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consultarSerie.setViewportView(tablaConsultarSerie);

        textoConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoConsultar.setText("Introduce el Identificador para consultar:");

        textFieldIdentificadorConsultador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorConsultadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldIdentificadorConsultador, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldIdentificadorConsultador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoConsultar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIdentificadorConsultadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorConsultadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorConsultadorActionPerformed

    public JTable getTablaConsultarSerie() {
        return tablaConsultarSerie;
    }

    public JTextField getTextFieldIdentificadorConsultador() {
        return textFieldIdentificadorConsultador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane consultarSerie;
    private javax.swing.JTable tablaConsultarSerie;
    private javax.swing.JTextField textFieldIdentificadorConsultador;
    private javax.swing.JLabel textoConsultar;
    // End of variables declaration//GEN-END:variables
}
